# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/da-programmer/Documents/black-jack/ui/newBlackJackUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Blackjack(object):
    def setupUi(self, Blackjack):
        Blackjack.setObjectName("Blackjack")
        Blackjack.resize(638, 288)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Blackjack)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playingSide = QtWidgets.QVBoxLayout()
        self.playingSide.setObjectName("playingSide")
        self.dealerSide = QtWidgets.QHBoxLayout()
        self.dealerSide.setObjectName("dealerSide")
        self.dealerLabel = QtWidgets.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dealerLabel.setFont(font)
        self.dealerLabel.setObjectName("dealerLabel")
        self.dealerSide.addWidget(self.dealerLabel)
        self.dCard_0 = QtWidgets.QLabel(Blackjack)
        self.dCard_0.setText("")
        self.dCard_0.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_0.setObjectName("dCard_0")
        self.dealerSide.addWidget(self.dCard_0)
        self.dCard_1 = QtWidgets.QLabel(Blackjack)
        self.dCard_1.setText("")
        self.dCard_1.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_1.setObjectName("dCard_1")
        self.dealerSide.addWidget(self.dCard_1)
        self.dCard_2 = QtWidgets.QLabel(Blackjack)
        self.dCard_2.setText("")
        self.dCard_2.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_2.setObjectName("dCard_2")
        self.dealerSide.addWidget(self.dCard_2)
        self.dCard_3 = QtWidgets.QLabel(Blackjack)
        self.dCard_3.setText("")
        self.dCard_3.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_3.setObjectName("dCard_3")
        self.dealerSide.addWidget(self.dCard_3)
        self.dCard_4 = QtWidgets.QLabel(Blackjack)
        self.dCard_4.setText("")
        self.dCard_4.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_4.setObjectName("dCard_4")
        self.dealerSide.addWidget(self.dCard_4)
        self.dCard_5 = QtWidgets.QLabel(Blackjack)
        self.dCard_5.setText("")
        self.dCard_5.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_5.setObjectName("dCard_5")
        self.dealerSide.addWidget(self.dCard_5)
        self.dCard_6 = QtWidgets.QLabel(Blackjack)
        self.dCard_6.setText("")
        self.dCard_6.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_6.setObjectName("dCard_6")
        self.dealerSide.addWidget(self.dCard_6)
        self.dCard_7 = QtWidgets.QLabel(Blackjack)
        self.dCard_7.setText("")
        self.dCard_7.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_7.setObjectName("dCard_7")
        self.dealerSide.addWidget(self.dCard_7)
        self.dCard_8 = QtWidgets.QLabel(Blackjack)
        self.dCard_8.setText("")
        self.dCard_8.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_8.setObjectName("dCard_8")
        self.dealerSide.addWidget(self.dCard_8)
        self.dCard_9 = QtWidgets.QLabel(Blackjack)
        self.dCard_9.setText("")
        self.dCard_9.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.dCard_9.setObjectName("dCard_9")
        self.dealerSide.addWidget(self.dCard_9)
        self.playingSide.addLayout(self.dealerSide)
        self.labDealer = QtWidgets.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labDealer.setFont(font)
        self.labDealer.setObjectName("labDealer")
        self.playingSide.addWidget(self.labDealer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.playingSide.addItem(spacerItem)
        self.playerSide = QtWidgets.QHBoxLayout()
        self.playerSide.setObjectName("playerSide")
        self.playerLabel = QtWidgets.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.playerLabel.setFont(font)
        self.playerLabel.setObjectName("playerLabel")
        self.playerSide.addWidget(self.playerLabel)
        self.pCard_0 = QtWidgets.QLabel(Blackjack)
        self.pCard_0.setText("")
        self.pCard_0.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_0.setObjectName("pCard_0")
        self.playerSide.addWidget(self.pCard_0)
        self.pCard_1 = QtWidgets.QLabel(Blackjack)
        self.pCard_1.setText("")
        self.pCard_1.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_1.setObjectName("pCard_1")
        self.playerSide.addWidget(self.pCard_1)
        self.pCard_2 = QtWidgets.QLabel(Blackjack)
        self.pCard_2.setText("")
        self.pCard_2.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_2.setObjectName("pCard_2")
        self.playerSide.addWidget(self.pCard_2)
        self.pCard_3 = QtWidgets.QLabel(Blackjack)
        self.pCard_3.setText("")
        self.pCard_3.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_3.setObjectName("pCard_3")
        self.playerSide.addWidget(self.pCard_3)
        self.pCard_4 = QtWidgets.QLabel(Blackjack)
        self.pCard_4.setText("")
        self.pCard_4.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_4.setObjectName("pCard_4")
        self.playerSide.addWidget(self.pCard_4)
        self.pCard_5 = QtWidgets.QLabel(Blackjack)
        self.pCard_5.setText("")
        self.pCard_5.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_5.setObjectName("pCard_5")
        self.playerSide.addWidget(self.pCard_5)
        self.pCard_6 = QtWidgets.QLabel(Blackjack)
        self.pCard_6.setText("")
        self.pCard_6.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_6.setObjectName("pCard_6")
        self.playerSide.addWidget(self.pCard_6)
        self.pCard_7 = QtWidgets.QLabel(Blackjack)
        self.pCard_7.setText("")
        self.pCard_7.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_7.setObjectName("pCard_7")
        self.playerSide.addWidget(self.pCard_7)
        self.pCard_8 = QtWidgets.QLabel(Blackjack)
        self.pCard_8.setText("")
        self.pCard_8.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_8.setObjectName("pCard_8")
        self.playerSide.addWidget(self.pCard_8)
        self.pCard_9 = QtWidgets.QLabel(Blackjack)
        self.pCard_9.setText("")
        self.pCard_9.setPixmap(QtGui.QPixmap("../cards/back.png"))
        self.pCard_9.setObjectName("pCard_9")
        self.playerSide.addWidget(self.pCard_9)
        self.playingSide.addLayout(self.playerSide)
        self.labPlayer = QtWidgets.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.labPlayer.setFont(font)
        self.labPlayer.setObjectName("labPlayer")
        self.playingSide.addWidget(self.labPlayer)
        self.horizontalLayout.addLayout(self.playingSide)
        self.bettingSide = QtWidgets.QVBoxLayout()
        self.bettingSide.setObjectName("bettingSide")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.bettingSide.addItem(spacerItem1)
        self.moneyLayout = QtWidgets.QHBoxLayout()
        self.moneyLayout.setObjectName("moneyLayout")
        self.moneyLabel_3 = QtWidgets.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.moneyLabel_3.setFont(font)
        self.moneyLabel_3.setObjectName("moneyLabel_3")
        self.moneyLayout.addWidget(self.moneyLabel_3)
        self.labMoney = QtWidgets.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labMoney.setFont(font)
        self.labMoney.setObjectName("labMoney")
        self.moneyLayout.addWidget(self.labMoney)
        self.bettingSide.addLayout(self.moneyLayout)
        self.betLabel = QtWidgets.QLabel(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.betLabel.setFont(font)
        self.betLabel.setObjectName("betLabel")
        self.bettingSide.addWidget(self.betLabel)
        self.betSpinBox = QtWidgets.QSpinBox(Blackjack)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.betSpinBox.setFont(font)
        self.betSpinBox.setMinimum(1)
        self.betSpinBox.setMaximum(99999999)
        self.betSpinBox.setObjectName("betSpinBox")
        self.bettingSide.addWidget(self.betSpinBox)
        self.labWarning = QtWidgets.QLabel(Blackjack)
        self.labWarning.setText("")
        self.labWarning.setObjectName("labWarning")
        self.bettingSide.addWidget(self.labWarning)
        self.btnBet = QtWidgets.QPushButton(Blackjack)
        self.btnBet.setObjectName("btnBet")
        self.bettingSide.addWidget(self.btnBet)
        self.btnDouble = QtWidgets.QPushButton(Blackjack)
        self.btnDouble.setObjectName("btnDouble")
        self.bettingSide.addWidget(self.btnDouble)
        self.btnHit = QtWidgets.QPushButton(Blackjack)
        self.btnHit.setObjectName("btnHit")
        self.bettingSide.addWidget(self.btnHit)
        self.btnStay = QtWidgets.QPushButton(Blackjack)
        self.btnStay.setObjectName("btnStay")
        self.bettingSide.addWidget(self.btnStay)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.bettingSide.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.bettingSide)

        self.retranslateUi(Blackjack)
        QtCore.QMetaObject.connectSlotsByName(Blackjack)

    def retranslateUi(self, Blackjack):
        _translate = QtCore.QCoreApplication.translate
        Blackjack.setWindowTitle(_translate("Blackjack", "Form"))
        self.dealerLabel.setText(_translate("Blackjack", "Dealer:"))
        self.labDealer.setText(_translate("Blackjack", "0"))
        self.playerLabel.setText(_translate("Blackjack", "Player:"))
        self.labPlayer.setText(_translate("Blackjack", "0"))
        self.moneyLabel_3.setText(_translate("Blackjack", "Money: $"))
        self.labMoney.setText(_translate("Blackjack", "500"))
        self.betLabel.setText(_translate("Blackjack", "Enter amount to bet:"))
        self.btnBet.setText(_translate("Blackjack", "Enter Bet"))
        self.btnDouble.setText(_translate("Blackjack", "Double"))
        self.btnHit.setText(_translate("Blackjack", "Hit"))
        self.btnStay.setText(_translate("Blackjack", "Stay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Blackjack = QtWidgets.QWidget()
    ui = Ui_Blackjack()
    ui.setupUi(Blackjack)
    Blackjack.show()
    sys.exit(app.exec_())

